hb_comment:
    resource: "@HBCommentBundle/Resources/config/routing.yml"
    prefix:   /

hb_private_message:
    resource: "@HBPrivateMessageBundle/Resources/config/routing.yml"
    prefix:   /

hb_search:
    resource: "@HBSearchBundle/Resources/config/routing.yml"
    prefix:   /

hb_news_feed:
    resource: "@HBNewsFeedBundle/Resources/config/routing.yml"
    prefix:   /news

hb_connect:
    resource: "@HBConnectBundle/Resources/config/routing.yml"
    prefix:   /

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: {_format: html }

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /optional_routing_prefix

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
    resource: "@HBConnectBundle/Resources/config/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

app:
    resource: @AppBundle/Controller/
    type:     annotation

_assetic:
    resource: .
    type:     assetic